import type { HardwareNodeTemplate, PriceQuote } from "../shared/types.js";

const observedAt = "2026-07-17T00:00:00.000Z";
export const HARDWARE_CATALOG_VERSION = "hardware-reference/2026-07-17.1";
export const HARDWARE_CATALOG_GENERATED_AT = observedAt;

export const HARDWARE_CATALOG: HardwareNodeTemplate[] = [
  {
    id: "ws-rtx4070tis-7950x",
    name: "Compact CUDA workstation",
    kind: "workstation",
    generation: "previous",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen 9 7950X",
    physicalCores: 16,
    motherboard: "X670E workstation board, 2× PCIe x16 physical",
    ramGb: 128,
    ecc: false,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA GeForce RTX 4070 Ti SUPER 16 GB",
    gpuCount: 1,
    gpuVramGbTotal: 16,
    localAiqSlots: 3,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 24,
    storageModel: "1× 2 TB NVMe for OS and temporary inference workspace",
    usableStorageTb: 2,
    diskWriteMbps: 700,
    nicGbps: 2.5,
    powerSupply: "1000 W 80 Plus Gold",
    cooling: "360 mm CPU liquid cooling and high-airflow GPU path",
    chassis: "Full tower",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 48,
    sources: [
      {
        title: "NVIDIA GeForce comparison",
        url: "https://www.nvidia.com/en-us/geforce/graphics-cards/compare/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtx5090-9950x",
    name: "Balanced Blackwell workstation",
    kind: "workstation",
    generation: "current",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen 9 9950X",
    physicalCores: 16,
    motherboard: "X870E workstation board, PCIe 5.0 x16",
    ramGb: 192,
    ecc: false,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA GeForce RTX 5090 32 GB",
    gpuCount: 1,
    gpuVramGbTotal: 32,
    localAiqSlots: 6,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 48,
    storageModel: "1× 4 TB NVMe for OS and temporary inference workspace",
    usableStorageTb: 4,
    diskWriteMbps: 1400,
    nicGbps: 10,
    powerSupply: "1600 W ATX 3.1 80 Plus Platinum",
    cooling: "360 mm CPU liquid cooling and dedicated GPU intake",
    chassis: "High-airflow full tower",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 62,
    sources: [
      {
        title: "NVIDIA GeForce RTX 5090 specifications",
        url: "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtxpro5000-trpro",
    name: "Expandable RTX PRO workstation",
    kind: "workstation",
    generation: "current",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 7975WX",
    physicalCores: 32,
    motherboard: "WRX90 workstation board with ECC and seven PCIe 5.0 slots",
    ramGb: 512,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 5000 Blackwell 72 GB",
    gpuCount: 1,
    gpuVramGbTotal: 72,
    localAiqSlots: 13,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 72,
    storageModel: "2× 4 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 4,
    diskWriteMbps: 2600,
    nicGbps: 25,
    powerSupply: "2000 W redundant-capable workstation PSU",
    cooling: "Workstation-class CPU loop and dual-slot blower GPU",
    chassis: "E-ATX workstation tower",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 90,
    sources: [
      {
        title: "NVIDIA RTX PRO desktop specifications",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-w7900-trpro",
    name: "Vulkan workstation (CPU RTSP decode)",
    kind: "workstation",
    generation: "previous",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 7975WX",
    physicalCores: 32,
    motherboard: "WRX90 workstation board with ECC",
    ramGb: 512,
    ecc: true,
    gpuVendor: "amd",
    gpuModel: "AMD Radeon PRO W7900 48 GB",
    gpuCount: 1,
    gpuVramGbTotal: 48,
    localAiqSlots: 9,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "2× 4 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 4,
    diskWriteMbps: 2400,
    nicGbps: 25,
    powerSupply: "1600 W 80 Plus Platinum",
    cooling: "Workstation CPU loop and triple-slot GPU airflow",
    chassis: "E-ATX workstation tower",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 82,
    sources: [
      {
        title: "AMD Radeon PRO W7900 specifications",
        url: "https://www.amd.com/en/products/graphics/workstations/radeon-pro/w7900.html",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "rack-2x-pro6000-xeon",
    name: "Dual-GPU RTX PRO rack server",
    kind: "rack",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "Intel Xeon 674X (28 cores)",
    physicalCores: 28,
    motherboard: "Single-socket Xeon 6 server platform, PCIe 5.0",
    ramGb: 512,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 6000 Blackwell Server Edition 96 GB",
    gpuCount: 2,
    gpuVramGbTotal: 192,
    localAiqSlots: 32,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 160,
    storageModel: "2× 3.84 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 3.84,
    diskWriteMbps: 5200,
    nicGbps: 25,
    powerSupply: "2× 2200 W hot-swap redundant",
    cooling: "4U high-static-pressure redundant fans",
    chassis: "4U GPU server",
    windowsEdition: "Ubuntu Server 24.04 LTS (Linux runtime port required)",
    expansionScore: 94,
    sources: [
      {
        title: "NVIDIA RTX PRO 6000 Blackwell family",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-6000-family/",
        observedAt,
      },
      {
        title: "Intel Xeon 6 product specifications",
        url: "https://www.intel.com/content/www/us/en/ark/products/series/240357/intel-xeon-6-processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "rack-4x-pro6000-dualxeon",
    name: "Dense four-GPU RTX PRO rack server",
    kind: "rack",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "2× Intel Xeon 6962P (144 cores total)",
    physicalCores: 144,
    motherboard: "Dual-socket Xeon 6 platform with four PCIe 5.0 x16 GPU links",
    ramGb: 1024,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 6000 Blackwell Server Edition 96 GB",
    gpuCount: 4,
    gpuVramGbTotal: 384,
    localAiqSlots: 64,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 320,
    storageModel: "2× 7.68 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 7.68,
    diskWriteMbps: 9600,
    nicGbps: 100,
    powerSupply: "4× 3000 W hot-swap, 2+2 redundant",
    cooling: "5U redundant high-static-pressure fan wall",
    chassis: "5U four-GPU server",
    windowsEdition: "Ubuntu Server 24.04 LTS (Linux runtime port required)",
    expansionScore: 100,
    sources: [
      {
        title: "NVIDIA RTX PRO 6000 Blackwell family",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-6000-family/",
        observedAt,
      },
      {
        title: "Intel Xeon 6 product specifications",
        url: "https://www.intel.com/content/www/us/en/ark/products/series/240357/intel-xeon-6-processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtxa6000-trpro5975wx",
    name: "Ampere ECC legacy-generation workstation",
    kind: "workstation",
    generation: "two_generations_back",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 5975WX",
    physicalCores: 32,
    motherboard: "WRX80 workstation board, 8-channel ECC DDR4",
    ramGb: 256,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX A6000 48 GB",
    gpuCount: 1,
    gpuVramGbTotal: 48,
    localAiqSlots: 8,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 48,
    storageModel: "2× 2 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 2,
    diskWriteMbps: 900,
    nicGbps: 10,
    powerSupply: "1200 W 80 Plus Platinum",
    cooling: "High-airflow tower with workstation CPU cooling",
    chassis: "Full tower workstation",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 78,
    sources: [
      {
        title: "NVIDIA RTX A6000 specifications",
        url: "https://www.nvidia.com/en-in/products/workstations/rtx-a6000/",
        observedAt,
      },
      {
        title: "AMD Ryzen Threadripper PRO 5975WX specifications",
        url: "https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen-threadripper-pro/ryzen-threadripper-pro-5000wx-series/amd-ryzen-threadripper-pro-5975wx.html",
        observedAt,
      },
    ],
  },
];

// Production quotes are collected or curated with source evidence. An empty seed prevents
// an unverified system price from being presented as market truth.
export const SEED_PRICE_QUOTES: PriceQuote[] = [];
