import type { HardwareNodeTemplate, PriceQuote } from "../shared/types.js";

const observedAt = "2026-07-17T16:00:00.000Z";
export const HARDWARE_CATALOG_VERSION = "hardware-reference/2026-07-17.3";
export const HARDWARE_CATALOG_GENERATED_AT = observedAt;

export const HARDWARE_CATALOG: HardwareNodeTemplate[] = [
  {
    id: "ws-rtx4070tis-7950x",
    name: "Compact CUDA workstation",
    kind: "workstation",
    generation: "previous",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen 9 7950X",
    physicalCores: 16,
    motherboard: "X670E workstation board, 2× PCIe x16 physical",
    ramGb: 128,
    ecc: false,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA GeForce RTX 4070 Ti SUPER 16 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 16,
    localAiqSlots: 3,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 24,
    storageModel: "1× 2 TB NVMe for OS and temporary inference workspace",
    usableStorageTb: 2,
    diskWriteMbps: 700,
    nicGbps: 2.5,
    powerSupply: "1000 W 80 Plus Gold",
    cooling: "360 mm CPU liquid cooling and high-airflow GPU path",
    chassis: "Full tower",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 48,
    sources: [
      {
        title: "NVIDIA GeForce comparison",
        url: "https://www.nvidia.com/en-us/geforce/graphics-cards/compare/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtx5090-9950x",
    name: "Balanced Blackwell workstation",
    kind: "workstation",
    generation: "current",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen 9 9950X",
    physicalCores: 16,
    motherboard: "X870E workstation board, PCIe 5.0 x16",
    ramGb: 192,
    ecc: false,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA GeForce RTX 5090 32 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 32,
    localAiqSlots: 6,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 48,
    storageModel: "1× 4 TB NVMe for OS and temporary inference workspace",
    usableStorageTb: 4,
    diskWriteMbps: 1400,
    nicGbps: 10,
    powerSupply: "1600 W ATX 3.1 80 Plus Platinum",
    cooling: "360 mm CPU liquid cooling and dedicated GPU intake",
    chassis: "High-airflow full tower",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 62,
    sources: [
      {
        title: "NVIDIA GeForce RTX 5090 specifications",
        url: "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtxpro5000-trpro",
    name: "Expandable RTX PRO workstation",
    kind: "workstation",
    generation: "current",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 7975WX",
    physicalCores: 32,
    motherboard: "WRX90 workstation board with ECC and seven PCIe 5.0 slots",
    ramGb: 512,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 5000 Blackwell 72 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 72,
    localAiqSlots: 13,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 72,
    storageModel: "2× 4 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 4,
    diskWriteMbps: 2600,
    nicGbps: 25,
    powerSupply: "2000 W redundant-capable workstation PSU",
    cooling: "Workstation-class CPU loop and dual-slot blower GPU",
    chassis: "E-ATX workstation tower",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 90,
    sources: [
      {
        title: "NVIDIA RTX PRO desktop specifications",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-w7900-trpro",
    name: "Vulkan workstation (CPU RTSP decode)",
    kind: "workstation",
    generation: "previous",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 7975WX",
    physicalCores: 32,
    motherboard: "WRX90 workstation board with ECC",
    ramGb: 512,
    ecc: true,
    gpuVendor: "amd",
    gpuModel: "AMD Radeon PRO W7900 48 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 48,
    localAiqSlots: 9,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "2× 4 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 4,
    diskWriteMbps: 2400,
    nicGbps: 25,
    powerSupply: "1600 W 80 Plus Platinum",
    cooling: "Workstation CPU loop and triple-slot GPU airflow",
    chassis: "E-ATX workstation tower",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 82,
    sources: [
      {
        title: "AMD Radeon PRO W7900 specifications",
        url: "https://www.amd.com/en/products/graphics/workstations/radeon-pro/w7900.html",
        observedAt,
      },
      {
        title: "AMD processor specifications",
        url: "https://www.amd.com/en/products/specifications/processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "rack-2x-pro6000-xeon",
    name: "Dual-GPU RTX PRO rack server",
    kind: "rack",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "Intel Xeon 674X (28 cores)",
    physicalCores: 28,
    motherboard: "Single-socket Xeon 6 server platform, PCIe 5.0",
    ramGb: 512,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 6000 Blackwell Server Edition 96 GB",
    gpuCount: 2,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 192,
    localAiqSlots: 32,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 160,
    storageModel: "2× 3.84 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 3.84,
    diskWriteMbps: 5200,
    nicGbps: 25,
    powerSupply: "2× 2200 W hot-swap redundant",
    cooling: "4U high-static-pressure redundant fans",
    chassis: "4U GPU server",
    operatingSystemFamily: "ubuntu",
    windowsEdition: "Ubuntu Server 24.04 LTS (Linux runtime port required)",
    expansionScore: 94,
    sources: [
      {
        title: "NVIDIA RTX PRO 6000 Blackwell family",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-6000-family/",
        observedAt,
      },
      {
        title: "Intel Xeon 6 product specifications",
        url: "https://www.intel.com/content/www/us/en/ark/products/series/240357/intel-xeon-6-processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "rack-4x-pro6000-dualxeon",
    name: "Dense four-GPU RTX PRO rack server",
    kind: "rack",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "2× Intel Xeon 6962P (144 cores total)",
    physicalCores: 144,
    motherboard: "Dual-socket Xeon 6 platform with four PCIe 5.0 x16 GPU links",
    ramGb: 1024,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX PRO 6000 Blackwell Server Edition 96 GB",
    gpuCount: 4,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 384,
    localAiqSlots: 64,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 320,
    storageModel: "2× 7.68 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 7.68,
    diskWriteMbps: 9600,
    nicGbps: 100,
    powerSupply: "4× 3000 W hot-swap, 2+2 redundant",
    cooling: "5U redundant high-static-pressure fan wall",
    chassis: "5U four-GPU server",
    operatingSystemFamily: "ubuntu",
    windowsEdition: "Ubuntu Server 24.04 LTS (Linux runtime port required)",
    expansionScore: 100,
    sources: [
      {
        title: "NVIDIA RTX PRO 6000 Blackwell family",
        url: "https://www.nvidia.com/en-us/products/workstations/professional-desktop-gpus/rtx-pro-6000-family/",
        observedAt,
      },
      {
        title: "Intel Xeon 6 product specifications",
        url: "https://www.intel.com/content/www/us/en/ark/products/series/240357/intel-xeon-6-processors.html",
        observedAt,
      },
    ],
  },
  {
    id: "ws-rtxa6000-trpro5975wx",
    name: "Ampere ECC legacy-generation workstation",
    kind: "workstation",
    generation: "two_generations_back",
    cpuVendor: "amd",
    cpuModel: "AMD Ryzen Threadripper PRO 5975WX",
    physicalCores: 32,
    motherboard: "WRX80 workstation board, 8-channel ECC DDR4",
    ramGb: 256,
    ecc: true,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA RTX A6000 48 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 48,
    localAiqSlots: 8,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 48,
    storageModel: "2× 2 TB enterprise NVMe, mirrored OS/temp workspace",
    usableStorageTb: 2,
    diskWriteMbps: 900,
    nicGbps: 10,
    powerSupply: "1200 W 80 Plus Platinum",
    cooling: "High-airflow tower with workstation CPU cooling",
    chassis: "Full tower workstation",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro for Workstations",
    expansionScore: 78,
    sources: [
      {
        title: "NVIDIA RTX A6000 specifications",
        url: "https://www.nvidia.com/en-in/products/workstations/rtx-a6000/",
        observedAt,
      },
      {
        title: "AMD Ryzen Threadripper PRO 5975WX specifications",
        url: "https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen-threadripper-pro/ryzen-threadripper-pro-5000wx-series/amd-ryzen-threadripper-pro-5975wx.html",
        observedAt,
      },
    ],
  },
  {
    id: "laptop-vivobook-s16-225h-16gb",
    name: "ASUS Vivobook S 16 entry laptop",
    kind: "laptop",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "Intel Core Ultra 5 225H (14 cores / 16 threads)",
    physicalCores: 14,
    sustainedComputeFactor: 0.25,
    ffmpegProcessesPerSecondCapacity: 10,
    inferenceRequestsPerSecondCapacity: 3,
    motherboard: "ASUS S5606CA mobile platform; Intel AI Boost NPU up to 13 TOPS",
    ramGb: 16,
    ecc: false,
    gpuVendor: "intel",
    gpuModel: "Integrated Intel Arc graphics",
    gpuCount: 1,
    memoryArchitecture: "shared",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "1 TB NVMe PCIe 4.0 for OS and temporary inference workspace",
    usableStorageTb: 1,
    diskWriteMbps: 650,
    nicGbps: 2.5,
    powerSupply: "USB-C mobile power adapter; wired 2.5 GbE adapter included in BOM",
    cooling: "Thin-laptop dual-fan cooling; sustained-load benchmark required",
    chassis: "16-inch mobile laptop",
    operatingSystemFamily: "ubuntu",
    windowsEdition: "Ubuntu 26.04 LTS (CPU decode; validate the exact installed build)",
    expansionScore: 8,
    sources: [{
      title: "ASUS Vivobook S 16 OLED S5606 technical specifications",
      url: "https://www.asus.com/laptops/for-home/vivobook/asus-vivobook-s-16-oled-s5606/techspec/",
      observedAt,
    }],
  },
  {
    id: "laptop-vivobook-s16-285h-32gb-user",
    name: "ASUS Vivobook S 16 OLED S5606CA — tested configuration",
    kind: "laptop",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "Intel Core Ultra 9 285H (16 cores / 16 threads, up to 5.4 GHz)",
    physicalCores: 16,
    sustainedComputeFactor: 0.35,
    ffmpegProcessesPerSecondCapacity: 16,
    inferenceRequestsPerSecondCapacity: 5,
    motherboard: "ASUS S5606CA; Intel AI Boost NPU 13 TOPS / 99 TOPS total theoretical (user supplied); user-observed Perceptrum execution",
    ramGb: 32,
    ecc: false,
    gpuVendor: "intel",
    gpuModel: "Intel Arc 140T integrated (8 Xe cores, shared memory)",
    gpuCount: 1,
    memoryArchitecture: "shared",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "WD PC SN5000S 1 TB NVMe PCIe 4.0 for OS and temporary inference workspace",
    usableStorageTb: 1,
    diskWriteMbps: 750,
    nicGbps: 2.5,
    powerSupply: "75 Wh battery / USB-C adapter; wired 2.5 GbE adapter included in BOM",
    cooling: "1.50 kg thin-laptop cooling; keep on AC power and validate sustained thermals",
    chassis: "ASUS Vivobook S 16 OLED S5606CA laptop",
    operatingSystemFamily: "ubuntu",
    windowsEdition: "Ubuntu 26.04 LTS, kernel 7.0, GNOME 50.1 / Wayland (user-tested)",
    expansionScore: 12,
    sources: [
      {
        title: "ASUS Vivobook S 16 OLED S5606 technical specifications",
        url: "https://www.asus.com/tw/laptops/for-home/vivobook/asus-vivobook-s-16-oled-s5606/techspec/",
        observedAt,
      },
      {
        title: "Configuration supplied and operationally observed by Aiquimist",
        url: "https://aiquimist.ai/",
        observedAt,
      },
    ],
  },
  {
    id: "laptop-zephyrus-g16-285h-rtx5070",
    name: "ASUS ROG Zephyrus G16 CUDA laptop",
    kind: "laptop",
    generation: "current",
    cpuVendor: "intel",
    cpuModel: "Intel Core Ultra 9 285H (16 cores / 16 threads)",
    physicalCores: 16,
    sustainedComputeFactor: 0.6,
    ffmpegProcessesPerSecondCapacity: 28,
    inferenceRequestsPerSecondCapacity: 8,
    motherboard: "ASUS GU605 mobile platform; Intel AI Boost NPU",
    ramGb: 32,
    ecc: false,
    gpuVendor: "nvidia",
    gpuModel: "NVIDIA GeForce RTX 5070 Laptop GPU 8 GB",
    gpuCount: 1,
    memoryArchitecture: "dedicated",
    gpuVramGbTotal: 8,
    localAiqSlots: 1,
    supportsPerceptrumGpuDecode: true,
    gpuDecode1080p30Streams: 12,
    storageModel: "2 TB NVMe PCIe 4.0 for OS and temporary inference workspace",
    usableStorageTb: 2,
    diskWriteMbps: 900,
    nicGbps: 2.5,
    powerSupply: "Mobile 200–240 W adapter; wired 2.5 GbE adapter included in BOM",
    cooling: "ROG vapor chamber / tri-fan cooling; benchmark at the selected power profile",
    chassis: "16-inch performance laptop",
    operatingSystemFamily: "windows",
    windowsEdition: "Windows 11 Pro",
    expansionScore: 14,
    sources: [{
      title: "ASUS ROG Zephyrus G16 (2025) GU605 specifications",
      url: "https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g16-2025-gu605/spec/",
      observedAt,
    }],
  },
  {
    id: "apple-mac-mini-m4-24gb",
    name: "Apple Mac mini M4 24 GB",
    kind: "mini_pc",
    generation: "current",
    cpuVendor: "apple",
    cpuModel: "Apple M4 (10-core CPU; 4 performance + 6 efficiency)",
    physicalCores: 10,
    sustainedComputeFactor: 0.45,
    ffmpegProcessesPerSecondCapacity: 12,
    inferenceRequestsPerSecondCapacity: 4,
    motherboard: "Apple M4 SoC with 16-core Neural Engine and hardware H.264/HEVC media engine",
    ramGb: 24,
    ecc: false,
    gpuVendor: "apple",
    gpuModel: "Apple M4 integrated 10-core GPU",
    gpuCount: 1,
    memoryArchitecture: "unified",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "512 GB integrated SSD for macOS and temporary inference workspace",
    usableStorageTb: 0.5,
    diskWriteMbps: 500,
    nicGbps: 10,
    powerSupply: "Integrated 155 W maximum continuous power supply",
    cooling: "Integrated Mac mini active cooling",
    chassis: "Mac mini 5-inch enclosure",
    operatingSystemFamily: "macos",
    windowsEdition: "macOS (Perceptrum macOS port and matching benchmark required)",
    expansionScore: 6,
    sources: [{ title: "Apple Mac mini technical specifications", url: "https://www.apple.com/mac-mini/specs/", observedAt }],
  },
  {
    id: "apple-mac-mini-m4pro-48gb",
    name: "Apple Mac mini M4 Pro 48 GB",
    kind: "mini_pc",
    generation: "current",
    cpuVendor: "apple",
    cpuModel: "Apple M4 Pro (14-core CPU; 10 performance + 4 efficiency)",
    physicalCores: 14,
    sustainedComputeFactor: 0.65,
    ffmpegProcessesPerSecondCapacity: 24,
    inferenceRequestsPerSecondCapacity: 7,
    motherboard: "Apple M4 Pro SoC with 16-core Neural Engine and hardware H.264/HEVC media engine",
    ramGb: 48,
    ecc: false,
    gpuVendor: "apple",
    gpuModel: "Apple M4 Pro integrated 20-core GPU",
    gpuCount: 1,
    memoryArchitecture: "unified",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "1 TB integrated SSD for macOS and temporary inference workspace",
    usableStorageTb: 1,
    diskWriteMbps: 750,
    nicGbps: 10,
    powerSupply: "Integrated 155 W maximum continuous power supply",
    cooling: "Integrated Mac mini active cooling",
    chassis: "Mac mini 5-inch enclosure",
    operatingSystemFamily: "macos",
    windowsEdition: "macOS (Perceptrum macOS port and matching benchmark required)",
    expansionScore: 10,
    sources: [{ title: "Apple Mac mini technical specifications", url: "https://www.apple.com/mac-mini/specs/", observedAt }],
  },
  {
    id: "apple-mac-studio-m4max-64gb",
    name: "Apple Mac Studio M4 Max 64 GB",
    kind: "workstation",
    generation: "current",
    cpuVendor: "apple",
    cpuModel: "Apple M4 Max (16-core CPU; 12 performance + 4 efficiency)",
    physicalCores: 16,
    sustainedComputeFactor: 0.8,
    ffmpegProcessesPerSecondCapacity: 36,
    inferenceRequestsPerSecondCapacity: 10,
    motherboard: "Apple M4 Max SoC with 16-core Neural Engine and dedicated media engines",
    ramGb: 64,
    ecc: false,
    gpuVendor: "apple",
    gpuModel: "Apple M4 Max integrated 40-core GPU",
    gpuCount: 1,
    memoryArchitecture: "unified",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "1 TB integrated SSD for macOS and temporary inference workspace",
    usableStorageTb: 1,
    diskWriteMbps: 1100,
    nicGbps: 10,
    powerSupply: "Integrated 480 W maximum continuous power supply",
    cooling: "Integrated Mac Studio high-throughput active cooling",
    chassis: "Mac Studio compact workstation",
    operatingSystemFamily: "macos",
    windowsEdition: "macOS (Perceptrum macOS port and matching benchmark required)",
    expansionScore: 14,
    sources: [{ title: "Apple Mac Studio technical specifications", url: "https://www.apple.com/mac-studio/specs/", observedAt }],
  },
  {
    id: "apple-mac-studio-m3ultra-96gb",
    name: "Apple Mac Studio M3 Ultra 96 GB",
    kind: "workstation",
    generation: "previous",
    cpuVendor: "apple",
    cpuModel: "Apple M3 Ultra (28-core CPU; 20 performance + 8 efficiency)",
    physicalCores: 28,
    sustainedComputeFactor: 0.85,
    ffmpegProcessesPerSecondCapacity: 64,
    inferenceRequestsPerSecondCapacity: 18,
    motherboard: "Apple M3 Ultra SoC with 32-core Neural Engine and two video decode engines",
    ramGb: 96,
    ecc: false,
    gpuVendor: "apple",
    gpuModel: "Apple M3 Ultra integrated 60-core GPU",
    gpuCount: 1,
    memoryArchitecture: "unified",
    gpuVramGbTotal: 0,
    localAiqSlots: 0,
    supportsPerceptrumGpuDecode: false,
    gpuDecode1080p30Streams: 0,
    storageModel: "1 TB integrated SSD for macOS and temporary inference workspace",
    usableStorageTb: 1,
    diskWriteMbps: 1300,
    nicGbps: 10,
    powerSupply: "Integrated 480 W maximum continuous power supply",
    cooling: "Integrated Mac Studio high-throughput active cooling",
    chassis: "Mac Studio compact workstation",
    operatingSystemFamily: "macos",
    windowsEdition: "macOS (Perceptrum macOS port and matching benchmark required)",
    expansionScore: 18,
    sources: [{ title: "Apple Mac Studio technical specifications", url: "https://www.apple.com/mac-studio/specs/", observedAt }],
  },
];

// Seller quotes are collected or imported separately. The engine's dated componentized
// reference-cost model is deliberately not represented as an in-stock seller quote.
export const SEED_PRICE_QUOTES: PriceQuote[] = [];
