import { SOURCE_REGISTRY_VERSION, type CatalogSource, type SourceRegistry } from "../shared/types.js";

const GENERATED_AT = "2026-07-18T12:00:00.000Z";

function source(
  id: string,
  organization: string,
  primaryUrl: string,
  category: CatalogSource["category"],
  parser: CatalogSource["parser"],
  products: string[],
  markets: CatalogSource["markets"] = [],
  currencies: CatalogSource["currencies"] = [],
  state: CatalogSource["state"] = "active",
  extraHosts: string[] = [],
  discoveryUrls: string[] = [],
): CatalogSource {
  const hostname = new URL(primaryUrl).hostname;
  return {
    id, organization, primaryUrl, discoveryUrls, allowedHosts: [hostname, ...extraHosts],
    allowedRedirectHosts: [hostname, ...extraHosts], category, markets, currencies, parser, products,
    trustTier: category === "price" ? 2 : 1, maxRequestsPerRun: category === "price" ? 80 : 30,
    minimumIntervalMs: 750, robotsRequired: parser !== "api", state,
    lastRunAt: null, lastSuccessAt: null, consecutiveFailures: 0,
    notes: state === "unavailable" ? ["Registrada para auditoria; coleta desativada enquanto exigir acesso interativo ou não autorizar automação."] : [],
  };
}

export const BUNDLED_SOURCE_REGISTRY: SourceRegistry = {
  schemaVersion: SOURCE_REGISTRY_VERSION,
  generatedAt: GENERATED_AT,
  sources: [
    source("spec-intel-ark", "Intel", "https://www.intel.com/content/www/us/en/products/sku/241060/intel-core-ultra-9-processor-285k-36m-cache-up-to-5-70-ghz/specifications.html", "specification", "html_table", ["CPU", "NPU", "iGPU"]),
    source("spec-amd-products", "AMD", "https://www.amd.com/en/products/processors/desktops/ryzen/9000-series/amd-ryzen-9-9950x.html", "specification", "html_table", ["CPU", "GPU", "APU"]),
    source("spec-nvidia-products", "NVIDIA", "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/", "specification", "html_table", ["GPU", "VRAM", "NVDEC", "NVENC"]),
    source("spec-apple-mac", "Apple", "https://www.apple.com/mac/", "specification", "json_ld", ["Apple Silicon", "Mac"]),
    source("spec-samsung-memory-storage", "Samsung Semiconductor", "https://semiconductor.samsung.com/consumer-storage/", "specification", "sitemap", ["memory", "SSD", "NVMe"], [], [], "unavailable"),
    source("spec-micron", "Micron", "https://www.micron.com/products", "specification", "sitemap", ["memory", "SSD", "NVMe"], [], [], "unavailable"),
    source("spec-crucial", "Crucial", "https://www.crucial.com/products", "specification", "json_ld", ["memory kit", "SSD"], [], [], "unavailable"),
    source("spec-kingston", "Kingston", "https://www.kingston.com/en/memory", "specification", "sitemap", ["memory kit", "SSD"], [], [], "unavailable"),
    source("spec-kioxia", "Kioxia", "https://americas.kioxia.com/en-us/business/ssd.html", "specification", "html_table", ["enterprise SSD", "NVMe"], [], [], "unavailable"),
    source("spec-solidigm", "Solidigm", "https://www.solidigm.com/products.html", "specification", "sitemap", ["client SSD", "data center SSD"], [], [], "unavailable"),
    source("spec-western-digital", "Western Digital", "https://www.westerndigital.com/products/internal-drives", "specification", "json_ld", ["SSD", "NVMe", "storage"], [], [], "unavailable"),
    source("spec-seagate", "Seagate", "https://www.seagate.com/products/enterprise-drives/", "specification", "json_ld", ["SSD", "retention storage"], [], [], "unavailable"),
    source("spec-asus-components", "ASUS", "https://www.asus.com/motherboards-components/", "specification", "sitemap", ["motherboard", "GPU", "PSU", "cooling", "chassis"], [], [], "unavailable"),
    source("spec-asrock-rack", "ASRock Rack", "https://www.asrockrack.com/general/products.asp", "specification", "html_table", ["server motherboard", "rack platform"], [], [], "unavailable"),
    source("spec-gigabyte-components", "Gigabyte", "https://www.gigabyte.com/Components", "specification", "sitemap", ["motherboard", "GPU", "PSU", "cooling", "chassis"], [], [], "unavailable"),
    source("spec-msi-components", "MSI", "https://www.msi.com/PC-Component", "specification", "sitemap", ["motherboard", "GPU", "PSU", "cooling", "chassis"], [], [], "unavailable"),
    source("spec-supermicro-components", "Supermicro", "https://www.supermicro.com/en/products", "specification", "sitemap", ["server motherboard", "chassis", "PSU", "cooling", "rack"], [], [], "unavailable"),
    source("spec-intel-ethernet", "Intel", "https://www.intel.com/content/www/us/en/products/details/ethernet.html", "specification", "html_table", ["NIC", "Ethernet controller"], [], [], "unavailable"),
    source("spec-broadcom-ethernet", "Broadcom", "https://www.broadcom.com/products/ethernet-connectivity/network-adapters", "specification", "html_table", ["NIC", "Ethernet adapter"], [], [], "unavailable"),
    source("spec-nvidia-networking", "NVIDIA Networking", "https://www.nvidia.com/en-us/networking/ethernet-adapters/", "specification", "html_table", ["NIC", "Ethernet adapter", "RDMA"], [], [], "unavailable"),
    source("spec-corsair-components", "Corsair", "https://www.corsair.com/us/en/c/pc-components", "specification", "json_ld", ["memory", "PSU", "cooling", "chassis", "SSD"], [], [], "unavailable"),
    source("spec-seasonic-psu", "Seasonic", "https://seasonic.com/consumer-power-supplies/", "specification", "html_table", ["PSU"], [], [], "unavailable"),
    source("spec-noctua-cooling", "Noctua", "https://noctua.at/en/products/cpu-cooler-retail", "specification", "html_table", ["cooling"], [], [], "unavailable"),
    source("oem-asus", "ASUS / ROG", "https://www.asus.com/laptops/for-gaming/rog-republic-of-gamers/", "oem", "sitemap", ["laptop", "desktop", "workstation"]),
    source("oem-dell", "Dell / Alienware / Precision / PowerEdge", "https://www.dell.com/en-us/shop/dell-computer-laptops/scr/laptops", "oem", "json_ld", ["laptop", "workstation", "server"], ["US"], ["USD"], "unavailable"),
    source("oem-hp", "HP", "https://www.hp.com/us-en/shop/cat/laptops", "oem", "json_ld", ["laptop", "workstation"], ["US"], ["USD"], "unavailable"),
    source("oem-hpe", "HPE", "https://www.hpe.com/us/en/servers.html", "oem", "sitemap", ["server"], ["US"], ["USD"], "unavailable"),
    source("oem-lenovo", "Lenovo / Legion / ThinkStation / ThinkSystem", "https://www.lenovo.com/us/en/c/workstations/", "oem", "json_ld", ["laptop", "workstation", "server"], ["US"], ["USD"], "unavailable"),
    source("oem-acer", "Acer / Predator", "https://www.acer.com/us-en/predator/laptops", "oem", "json_ld", ["laptop", "desktop"], ["US"], ["USD"], "unavailable"),
    source("oem-msi", "MSI", "https://us.msi.com/Laptops", "oem", "sitemap", ["laptop", "desktop", "workstation"], ["US"], ["USD"], "unavailable"),
    source("oem-gigabyte", "Gigabyte / Aorus", "https://www.gigabyte.com/Laptop", "oem", "sitemap", ["laptop", "workstation", "server"], [], [], "unavailable"),
    source("oem-supermicro", "Supermicro", "https://www.supermicro.com/en/products/systems", "oem", "sitemap", ["workstation", "server"]),
    source(
      "benchmark-mlcommons",
      "MLCommons",
      "https://raw.githubusercontent.com/mlcommons/inference_results_v6.0/main/summary_results.json",
      "benchmark",
      "api",
      ["local_inference", "Qwen3-VL", "GPU"],
    ),
    source("benchmark-openbenchmarking", "OpenBenchmarking", "https://openbenchmarking.org/suites/", "benchmark", "api", ["CPU", "GPU", "storage", "memory"], [], [], "unavailable"),
    source("benchmark-openbenchmarking-stream", "OpenBenchmarking / STREAM", "https://openbenchmarking.org/test/pts/stream", "benchmark", "html_table", ["memory_bandwidth"]),
    source("benchmark-openbenchmarking-fio", "OpenBenchmarking / fio", "https://openbenchmarking.org/test/pts/fio", "benchmark", "html_table", ["disk_read", "disk_write", "IOPS", "latency"]),
    source("benchmark-openbenchmarking-ffmpeg", "OpenBenchmarking / FFmpeg", "https://openbenchmarking.org/test/pts/ffmpeg", "benchmark", "html_table", ["video_decode", "video_encode", "CPU"]),
    source("benchmark-openbenchmarking-opencv", "OpenBenchmarking / OpenCV", "https://openbenchmarking.org/test/pts/opencv", "benchmark", "html_table", ["bgr_processing", "CPU"]),
    source("benchmark-blender", "Blender Open Data", "https://opendata.blender.org/", "benchmark", "html_table", ["CPU", "GPU"], [], [], "active", [], [
      "https://opendata.blender.org/devices/NVIDIA%20GeForce%20RTX%204070%20Ti%20SUPER/",
      "https://opendata.blender.org/devices/NVIDIA%20GeForce%20RTX%205090/",
      "https://opendata.blender.org/devices/NVIDIA%20RTX%206000%20Ada%20Generation/",
      "https://opendata.blender.org/devices/Apple%20M4%20Pro/"
    ]),
    source("benchmark-spec", "SPEC", "https://www.spec.org/cpu2017/results/res2025q1/cpu2017-20250126-46110.csv", "benchmark", "csv", ["CPU sustained"], [], [], "active", [], [
      "https://www.spec.org/cpu2017/results/res2025q1/cpu2017-20250126-46114.csv",
      "https://www.spec.org/cpu2017/results/res2025q1/cpu2017-20250127-46190.csv",
    ]),
    source("benchmark-nvidia-codec", "NVIDIA Video Codec SDK", "https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new", "benchmark", "html_table", ["NVDEC", "NVENC"]),
    source("benchmark-intel-vpl", "Intel Video Processing Library", "https://www.intel.com/content/www/us/en/developer/tools/vpl/overview.html", "benchmark", "html_table", ["Intel decode", "Intel encode", "video processing"]),
    source("benchmark-amd-video", "AMD Video and Streaming", "https://www.amd.com/en/products/software/adrenalin/video-streaming.html", "benchmark", "html_table", ["AMD VCN", "H.264", "H.265", "AV1"]),
    source("benchmark-apple-videotoolbox", "Apple VideoToolbox", "https://developer.apple.com/documentation/videotoolbox", "benchmark", "html_table", ["Apple hardware decode", "Apple hardware encode"]),
    source("price-br-dell", "Dell Brasil", "https://www.dell.com/pt-br/shop", "price", "json_ld", ["systems"], ["BR"], ["BRL"]),
    source("price-br-hp", "HP Brasil", "https://www.hp.com/br-pt/shop/", "price", "json_ld", ["systems"], ["BR"], ["BRL"], "unavailable"),
    source("price-br-lenovo", "Lenovo Brasil", "https://www.lenovo.com/br/pt/", "price", "json_ld", ["systems"], ["BR"], ["BRL"], "unavailable"),
    source("price-br-asus", "ASUS Brasil", "https://br.store.asus.com/", "price", "json_ld", ["systems", "components"], ["BR"], ["BRL"], "unavailable"),
    source("price-br-apple", "Apple Brasil", "https://www.apple.com/br/shop/buy-mac", "price", "json_ld", ["systems"], ["BR"], ["BRL"]),
    source("price-br-kabum", "KaBuM!", "https://www.kabum.com.br/hardware", "price", "json_ld", ["components", "systems"], ["BR"], ["BRL"]),
    source("price-br-pichau", "Pichau", "https://www.pichau.com.br/hardware", "price", "json_ld", ["components", "systems"], ["BR"], ["BRL"], "unavailable"),
    source("price-br-terabyte", "TerabyteShop", "https://www.terabyteshop.com.br/hardware", "price", "json_ld", ["components", "systems"], ["BR"], ["BRL"], "unavailable"),
    source("price-us-nvidia", "NVIDIA Marketplace", "https://marketplace.nvidia.com/en-us/consumer/", "price", "json_ld", ["GPU", "systems"], ["US"], ["USD"], "unavailable"),
    source("price-us-newegg", "Newegg", "https://www.newegg.com/Components/Store/ID-1", "price", "json_ld", ["components", "systems"], ["US"], ["USD"]),
    source("price-us-apple", "Apple", "https://www.apple.com/shop/buy-mac/mac-mini/m4-pro-chip-14-core-cpu-20-core-gpu-48gb-memory-1tb-storage", "price", "json_ld", ["systems"], ["US"], ["USD"]),
    source("price-us-bh", "B&H", "https://www.bhphotovideo.com/c/browse/computers-solutions/ci/9581", "price", "json_ld", ["components", "systems"], ["US"], ["USD"], "unavailable"),
    source("price-us-bestbuy", "Best Buy", "https://www.bestbuy.com/site/computers-pcs/computer-cards-components/abcat0507000.c", "price", "json_ld", ["components", "systems"], ["US"], ["USD"], "unavailable"),
    source("price-de-alternate", "Alternate", "https://www.alternate.de/Hardware", "price", "json_ld", ["components", "systems"], ["DE"], ["EUR"]),
    source("price-de-apple", "Apple", "https://www.apple.com/de/shop/buy-mac/mac-mini/m4-chip-10%E2%80%91core-cpu-10%E2%80%91core-gpu-24-gb-arbeitsspeicher-1tb-speicher", "price", "json_ld", ["systems"], ["DE"], ["EUR"]),
    source("price-de-cyberport", "Cyberport", "https://www.cyberport.de/pc-und-zubehoer.html", "price", "json_ld", ["components", "systems"], ["DE"], ["EUR"], "unavailable"),
    source("price-de-notebooksbilliger", "notebooksbilliger", "https://www.notebooksbilliger.de/pc+hardware", "price", "json_ld", ["components", "systems"], ["DE"], ["EUR"], "unavailable"),
    source("price-de-mindfactory", "Mindfactory", "https://www.mindfactory.de/Hardware.html", "price", "json_ld", ["components"], ["DE"], ["EUR"], "unavailable"),
    source("fx-bcb-ptax", "Banco Central do Brasil", "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/aplicacao#!/recursos", "exchange_rate", "api", ["USD/BRL", "EUR/BRL"], ["BR"], ["BRL"]),
    source("fx-ecb", "European Central Bank", "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml", "exchange_rate", "api", ["EUR/USD"], ["DE", "US"], ["EUR", "USD"]),
    source("fx-federal-reserve", "Federal Reserve", "https://www.federalreserve.gov/releases/h10/current/", "exchange_rate", "html_table", ["USD/EUR"], ["US", "DE"], ["USD", "EUR"]),
  ],
};
